version: "3"
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: videgrenier
      MYSQL_ROOT_PASSWORD: videgrenier1234
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: videgrenier1234
    ports:
      - "8080:80"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./public/index.php:/var/www/html
      - ./public/.htaccess:/var/www/html/.htaccess
    depends_on:
      - db
volumes:
  myvolume: